version: '3'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    # restart: always
    environment:
      MYSQL_DATABASE: 'microblog'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'djdf1605'
      MYSQL_ROOT_PASSWORD: 'djdf1605'
  web:
    build: ./Backend
    command: python microblog/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Backend:/back
    ports:
      - "8000:8000"
    depends_on:
      - db
  front:
    build: ./Frontend
    volumes:
      - ./Frontend:/front
      - /front/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    command: npm start
    stdin_open: true
  
