# Generated by Django 3.1.2 on 2020-11-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='followers',
            field=models.ManyToManyField(related_name='acc_followers', to='api.Account'),
        ),
    ]
