# Generated by Django 3.1.2 on 2020-11-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_account_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='followers',
            field=models.ManyToManyField(default=None, related_name='acc_followers', to='api.Account'),
        ),
    ]
