# Generated by Django 3.1.2 on 2020-11-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20201124_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='followers',
        ),
        migrations.AddField(
            model_name='account',
            name='following',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='followers', to='api.Account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='link',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='location',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
